### ISSUE TITLE
how to add ulister into plugins

### ISSUE THREAD

**Issue by SheldonXLD** [AlexanderPro/Wlx2Explorer#1]
Hi, 
    I'm new to Wlx2Explorer, and how to add ulister into plugins?
    should I download x64 version of ulister and oracle's Viewer Technology 8.5.4  if I use your newest release?
    Thanks very much

**Comment by AlexanderPro** [comment]
Hi,
You can use current and previous versions of Wlx2Explorer and Viewer Technology. 
The main rule is for 32 bit plugin you need to use 32 bit Wlx2Explorer and 32 bit Viewer Technology. 
For 64 bit plugin use 64 bit Wlx2Explorer and Viewer Technology.
For 32 bit plugin please use the following steps:
1. Download Wlx2Explorer (https://github.com/AlexanderPro/Wlx2Explorer/releases/download/v1.1.7110.21758/Wlx2Explorer_v1.1.7110.21758.zip) It is a 32 bit version. Unzip it.
2. Download 32 bit ulister plugin (http://wincmd.ru/files/wlx_uLister_4.0.0.zip) Unzip it.
3. Download 32 bit Viewer Technology (https://www.oracle.com/technetwork/middleware/content-management/downloads/oit-dl-otn-097435.html) Unzip it. Copy "redist" subfolder to plugin folder.
4. Run Wlx2Explorer. Open Settings dialog from the System Tray. Add the plugin on the corresponding tab. In the this tab up an item by arrow button to the top. Press Ok.
5. Open Window Explorer. Select .doc, .zip or other Viewer Technology file and press Ctrl+Q keys.
