### ISSUE TITLE
Is this standalone or does it require Total Commander to work?

### ISSUE THREAD

**Issue by pa-0** [AlexanderPro/Wlx2Explorer#12]
Hi, I've been looking everywhere for a viewer that can consume the OIVT library, so this looks amazing! I'm just curious if it requires that I install Total Commander as well, or is it a standalone shell extension?

**Comment by AlexanderPro** [comment]
Hi @pa-0,

You need only .net framework 4 and .wlx plugin files.

**Comment by pa-0** [comment]
Thanks @AlexanderPro
