### ISSUE TITLE
Failed to load wlx_uLister_4.0.0 x64

### ISSUE THREAD

**Issue by toebylin** [AlexanderPro/Wlx2Explorer#3]
Hi Alexander,
How are you? I am using Wlx2Explorer on my window 7 computer (32 bit), everything goes well.  I tried to load Ulister x64 on my laptop (windows10 64 bit) but failed. I found a tutorial on using Wlx2Explorer in China that says there are 32-bit and 64-bit versions, but I can not found the x64 version in the release page, could you help me? Thank you.

**Comment by AlexanderPro** [comment]
Hi toebylin,

Please, try this version [1.2.1 x86-64](https://github.com/AlexanderPro/Wlx2Explorer/releases/download/v1.2.1/Wlx2Explorer_x86_64_v1.2.1.zip). I have tested it with Ulister x64 and Viewer Technology, and everything works fine.

— Regards, 
Alexander Illarionov
