### ISSUE TITLE
Can't open with cudalister when the file name contain chinese characters

### ISSUE THREAD

**Issue by netdog2019** [AlexanderPro/Wlx2Explorer#5]
Can't open with cudalister when the file name contain chinese characters. But can open with SynWrite 6.40 even the file name contain chinese characters. 
When i copy the wlx_cudalister_1.6.18 to TC plugin, which is fine when i open a file with chinses characters.

Win 10 64x
wlx_cudalister_1.6.18_32x
Wlx2Explorer_x32_v1.2.2

i have also test 64x, the same problem.

**Comment by netdog2019** [comment]
But SynWrite is too flow compared to cudalister when open a same file.

**Comment by netdog2019** [comment]
If the file name only contain english characters, It's fine when open with cudalister, very fast.

**Comment by AlexanderPro** [comment]
Hi netdog2019,

Try this version [1.3.1](https://github.com/AlexanderPro/Wlx2Explorer/releases/tag/v1.3.1). But some plugins without Unicode functions can not work properly with chinese characters. I will try to fix it in the next versions.

**Comment by netdog2019** [comment]
It's ok now, thank your very much.
It's a very good software.
