### ISSUE TITLE
fail to load mthumbs.wlx x64

### ISSUE THREAD

**Issue by Pupoin** [AlexanderPro/Wlx2Explorer#7]
Hi, Alexander, that is a excellent software for me. faster than seer of quicklook.
but  I fail to load the plugin [mthumbs.wlx](https://totalcmd.net/plugring/mthumbs.wlx.html) .

My os system is windows10, using wlx2explore latest version x64.

**Comment by Pupoin** [comment]
when I load [DirSizeCalc Charts 1.10 (Lister plugin)](https://www.ghisler.ch/board/viewtopic.php?t=42391&sid=2623e3c584d85cd1f33bde0842627d8b), press ctrl+Q, there is nothing happend. x86 version is the same situation. However,  in total command software, the plugin works.

**Comment by AlexanderPro** [comment]
Hi [Pupoin](https://github.com/Pupoin),

Please, try [1.5.0](https://github.com/AlexanderPro/Wlx2Explorer/releases/tag/v1.5.0) version for mthumbs.wlx plugin. Unfortunately, I haven't been able to determine the error for DirSizeCalc Charts 1.10 plugin and I don't know how to fix it yet.
