### ISSUE TITLE
hope to support command-line mode？

### ISSUE THREAD

**Issue by sullevy** [AlexanderPro/Wlx2Explorer#8]
So that：can use AHK, Quicker and other software, passing parameters, to use this software in different Apps,eg. Everything. THKS

**Comment by AlexanderPro** [comment]
Hi [sullevy](https://github.com/sullevy),

Please, try [1.5.0](https://github.com/AlexanderPro/Wlx2Explorer/releases/tag/v1.5.0) version.

```bash
-h --help             The help
-f --file             Path to file
-s --suppressmsg      Suppress messages

Example:
Wlx2Explorer.exe -s --file "C:\Temp\Image.jpeg"
```
