### ISSUE TITLE
Bugs when open new tab in explorere.exe on windows11

### ISSUE THREAD

**Issue by Pupoin** [AlexanderPro/Wlx2Explorer#9]
When I open several tabs in explorer.exe on windows11, Sometimes the file can not be open correctly. It looks like the wlx2explorer.exe cannot find the right file path.

**Comment by AlexanderPro** [comment]
Hi @Pupoin,

Please, try version [1.6.0](https://github.com/AlexanderPro/Wlx2Explorer/releases/tag/v1.6.0).
